### ISSUE TITLE
NPM start?

### ISSUE THREAD

**Issue by BasharAG** [adamalawrence/Ostia#25]
I ran the NPM Start command, but I am curious as to which port I should access the application at. Here is the output of the command:
```

 npm start

> Ostia@0.0.0 start /home/ubuntu/Ostia
> node server.js

```

**Comment by adamlawrencium** [comment]
Navigate to [http://localhost:3000/dashboard](http://localhost:3000/dashboard) in your web browser. You may need to refresh the page a few seconds after running ```npm start``` to let all the data load.
