### ISSUE TITLE
GDAX Parsing not working

### ISSUE THREAD

**Issue by BirchellE** [adamalawrence/Ostia#9]
For some reason GDAX parsing does not work (ie. the high bid and low ask does not line up with the GDAX website high bid and low ask), this could be for a number of reasons, namely, incorrect mapParsing, incorrect data parsing, or a host of other reasons.

**Comment by Mingling94** [comment]
Is this still an issue? Seems to be fine on my end. Can you post a screenshot of a reproduction of the erroneous values? @BirchellE

**Comment by BirchellE** [comment]
Fixed it in my new branch, not sure where I was going wrong with Level 3 Orderbook parsing, but it works fine with Level 2.
